### PR TITLE
Model Saving

### PR DESCRIPTION
**Pull request by jfkirk**
Addresses https://github.com/jfkirk/tensorrec/issues/8

1. Adds methods for saving/loading the TensorRec object and the TensorFlow session behind it.

2. Adds a test for the saving/loading methods.

3. Refactors graph hook management to be done with lists of attr/node names. This allows us to quickly strip all hooks from the Python object before serializing it.

4. Removes many unnecessary graph hooks. A hook was necessary if it was used to power an API function outside of graph construction.

### CODE REVIEW

**Comment by jfkirk** [comment]
CC @mesanders

**Comment by jcauteru** [comment]
hi @mesanders

I have some very useless comments. LGTM! :shipit:

**Comment by jcauteru** [comment]
I can also look more at it later if you want a deeper review. I mainly looked at the renaming and the saving, restore functions.

**Comment by jfkirk** [comment]
@jcauteru added a few more small commits - LMK if you think this is good to merge.

**Comment by jcauteru** [comment]
:+1:

**Comment by jfkirk** [comment]
I noticed and fixed a bug where the model breaks after being saved because the graph hooks were broken. I'll merge after Travis passes.

**Pull request merged**
