### PR TITLE
API: Makes prediction functions configurable

### PR DESCRIPTION
**Pull request by jfkirk**
Another doozy. This PR:

1. Adds an API for configuring prediction functions, and implements dot-product and cosine-distance prediction.
2. Removes old alignment API in favor of dot-product prediction functions.
3. Adds top level API methods to do dot product and cosine distance, regardless of prediction configuration.
4. Changes loss_graph API to accept objects, not classes.
5. Removes WMRBAlignmentLossGraph.
6. Various tests.

### CODE REVIEW

**Comment by jcauteru** [comment]
going to have to go through this one in stages

**Comment by jfkirk** [comment]
Building on this doozy: I've added EuclidianDistancePredictionGraph and a fun script to plot some movies from movielens

**Comment by jfkirk** [comment]
This has become a behemoth. Somebody stop me. Please.

**Comment by jfkirk** [comment]
ezgif-3-5704bc047b

**Pull request merged**
