### PR TITLE
Jcaut/ndcg

### PR DESCRIPTION
**Pull request by jcauteru**
@jfkirk 
@mesanders 

more tests and shorter names for james :-)

### CODE REVIEW

**Comment by jcauteru** [comment]
@jfkirk 

```Traceback (most recent call last):
  File "/home/travis/build/jfkirk/tensorrec/test/test_tensorrec.py", line 65, in test_predict_alignment
    self.assertGreaterEqual(val, -1.0)
AssertionError: -1.0359185 not greater than or equal to -1.0```

**Comment by jfkirk** [comment]
@jcauteru That method and test don't exist anymore (the error was an old transient from the broken cos distance implementation). Rebase and it will go away.

**Comment by jfkirk** [comment]
Besides the rebase, LGTM! 👍 Mind rebasing so we can ensure Travis passes?

**Comment by jcauteru** [comment]
:shipit:

**Pull request merged**
